name: Delete Merged Branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete merged branch
        if: github.event.pull_request.merged == true
        run: |
          echo "Pull request #${{ github.event.pull_request.number }} was merged"
          echo "Deleting branch: ${{ github.event.pull_request.head.ref }}"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} || echo "Branch already deleted"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout repository
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Delete all merged branches (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Checking for branches that are fully merged into main..."
          git fetch --all
          
          # Get all remote branches except main and HEAD
          for branch in $(git branch -r --merged origin/main | grep -v 'HEAD' | grep -v 'main' | sed 's/origin\///'); do
            echo "Deleting merged branch: $branch"
            git push origin --delete "$branch" || echo "Failed to delete $branch (may already be deleted)"
          done
          
          echo "Cleanup complete!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
